server:
  port: 9003

spring:
  application:
    name: seata-account-server

  cloud:
    #nacos相关配置
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 7610c613-f7c3-41b3-a67a-93c0a7e93268
        group: seata-test
      config:
        server-addr: localhost:8848
        namespace: 7610c613-f7c3-41b3-a67a-93c0a7e93268
        group: seata-test

  datasource:
    #数据源基本配置
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_account?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    druid:
      #配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      #CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 20
      #最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      #设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      #设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      #可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#分布式事务 seata 配置
seata:
  service:
    vgroup-mapping:
      #default_tx_group分组名称必须要跟tx-service-group的值一样
      default_tx_group: default
  #指定事务分组 分组必须在 nacos seataServer.properties配置中有
  tx-service-group: default_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: seata-test
      namespace: 7610c613-f7c3-41b3-a67a-93c0a7e93268
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: seata-test
      namespace: 7610c613-f7c3-41b3-a67a-93c0a7e93268
      username: nacos
      password: nacos

# seata 日志配置
logging:
  level:
    io:
      seata: info