server:
  port: 9001

spring:
  application:
    name: seata-order-server

  cloud:
    #    alibaba:
    #      seata:
    #        tx-service-group: default_tx_group # seata 服务事务分组
    #nacos相关配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 7610c613-f7c3-41b3-a67a-93c0a7e93268
        group: seata-test
      config:
        server-addr: 127.0.0.1:8848
        namespace: 7610c613-f7c3-41b3-a67a-93c0a7e93268
        group: seata-test

  datasource:
    #数据源基本配置
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_order?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    druid:
      #配置初始化大小、最小、最大线程数
      initialSize: 5
      minIdle: 5
      #CPU核数+1，也可以大些但不要超过20，数据库加锁时连接过多性能下降
      maxActive: 20
      #最大等待时间，内网：800，外网：1200（三次握手1s）
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最大空间时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      #设置从连接池获取连接时是否检查连接有效性，true检查，false不检查
      testOnBorrow: true
      #设置从连接池归还连接时是否检查连接有效性，true检查，false不检查
      testOnReturn: true
      #可以支持PSCache（提升写入、查询效率）
      poolPreparedStatements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      #保持长连接
      keepAlive: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


feign:
  hystrix:
    #开启feign调用时的服务中断处理机制
    enabled: true
  client:
    config:
      default:
        #设置 feign 连接超时时间
        connectTimeout: 3000
        #设置 feign 读取超时时间
        readTimeout: 3000

#feignClient 调用服务名称+地址
interface:
  storage:
    serverName: seata-storage-server
    serverHost: 127.0.0.1:9002
  account:
    serverName: seata-account-server
    serverHost: 127.0.0.1:9003

#熔断超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  #请求连接的超时时间
  ConnectTimeout: 60000
  #请求处理的超时时间
  ReadTimeout: 60000
  #对当前实例的重试次数
  MaxAutoRetries: 0
  #切换实例的重试次数 1
  MaxAutoRetriesNextServer: 1

#分布式事务 seata 配置
seata:
  #  service:
  #    vgroup-mapping:
  #default_tx_group分组名称必须要跟tx-service-group的值一样
  #      default_tx_group: default
  #指定事务分组 分组必须在 nacos seataServer.properties配置中有
  tx-service-group: default_tx_group
  config:
    # 配置seata配置中心，告诉我们的seata client读取我们的seata server（TC）的配置
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: seata-test
      namespace: 7610c613-f7c3-41b3-a67a-93c0a7e93268
      username: nacos
      password: nacos
  registry:
    # 配置seata注册中心，告诉我们的seata client怎么去访问我们的seata server（TC）
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: seata-test
      namespace: 7610c613-f7c3-41b3-a67a-93c0a7e93268
      username: nacos
      password: nacos

# seata 日志配置
logging:
  level:
    io:
      seata: info